/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import javax.swing.JOptionPane;

/**
 *
 * @author Mahtab Kazmi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsersName = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        Pass1 = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        userName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(0, 153, 153));
        userName.setText("User Name");
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(0, 153, 153));
        Pass.setText("Password");
        Pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        submit.setBackground(new java.awt.Color(0, 255, 255));
        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 153, 153));
        submit.setText("Submit");
        submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        category.setBackground(new java.awt.Color(0, 255, 255));
        category.setForeground(new java.awt.Color(0, 153, 153));
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher", "Student" }));
        category.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Pass1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pass1.setForeground(new java.awt.Color(0, 153, 153));
        Pass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass1.setText("Select Option");
        Pass1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        display.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        display.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17))
                            .addComponent(Pass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(category, 0, 164, Short.MAX_VALUE)
                            .addComponent(UsersName)
                            .addComponent(Password))
                        .addGap(28, 28, 28)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(display)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pass1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsersName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String UName=UsersName.getText();
        String password=new String(Password.getPassword());
        String Cat=category.getSelectedItem().toString();
        
        if (Cat.equals("Student") && UName.equals("Student") && password.equals("Student")) {
                JOptionPane.showMessageDialog(this, "Student Successfully Login");
                display.setText(UName);
        }else if (Cat.equals("Teacher") && UName.equals("Teacher") && password.equals("Teacher")) {
                JOptionPane.showMessageDialog(this, "Teacher Successfully Login");
                display.setText(UName);
            
        }else if((!Cat.equals("Teacher") && (UName.equals("Teacher") && password.equals("Teacher"))) || (!Cat.equals("Student") && (UName.equals("Student") && password.equals("Student")))){
                JOptionPane.showMessageDialog(this, "You Select wrong Option");
                display.setText("You Select wrong Option");
        }
        else {
            JOptionPane.showMessageDialog(this, "UserName Or Password is Wrong");
            display.setText("UserName Or Password is Wrong");
        }
        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Pass1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UsersName;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel display;
    private javax.swing.JButton submit;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
